Book 1  
Chapter 7 Control Flow Statements in Python
### 使用 NumPy 计算矩阵乘法

In [2]:
import numpy as np

# 定义矩阵 A 和 B
A = np.array([[1, 2, 10, 20],
              [3, 4, 30, 40, ]])
B = np.array([[1, 3],
              [2, 4],
              [10, 30],
              [20, 40]])

In [3]:
C = A @ B
print(C)

[[ 505 1111]
 [1111 2525]]


In [4]:
D = B @ A
print(D)

[[  10   14  100  140]
 [  14   20  140  200]
 [ 100  140 1000 1400]
 [ 140  200 1400 2000]]


In [5]:
# 比较自定义和 NumPy 矩阵乘法运算用时
from numpy.random import randint
import time

num = 200

# num * num 大小方阵，0~9随机数
A = randint(0, 10, size = (num, num))
B = randint(0, 10, size = (num, num))

# 使用 NumPy 计算矩阵乘法
start_time = time.time() # 开始时刻
C_1 = A @ B
stop_time = time.time() # 结束时刻
time_used = stop_time - start_time
print('--- %s seconds ---' % time_used)

# 手动计算矩阵乘法
C = np.zeros((num, num)) # num * num 大小全0方阵
start_time = time.time()
for i in range(num):
    for j in range(num):
        for k in range(num):
            C[i][j] += A[i][k] * B[k][j]
stop_time = time.time()
time_used = stop_time - start_time
print('--- %s seconds ---' % time_used)

--- 0.0028450489044189453 seconds ---
--- 2.828805923461914 seconds ---
